# Generated by Django 5.1.1 on 2024-11-05 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=10)),
                ('loginid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('number', models.CharField(max_length=10)),
                ('role', models.CharField(default='merchant', max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('store_name', models.CharField(max_length=100)),
                ('business_license', models.CharField(max_length=100)),
                ('loginid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_register', to='user.login')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('number', models.CharField(max_length=10)),
                ('role', models.CharField(default='user', max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('loginid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='register', to='user.login')),
            ],
        ),
    ]
