# Generated by Django 5.1.1 on 2024-09-26 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='role',
            field=models.CharField(default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='MerchantRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('number', models.CharField(max_length=10)),
                ('role', models.CharField(default='merchant', max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('store_name', models.CharField(max_length=100)),
                ('business_license', models.CharField(max_length=100)),
                ('loginid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.login')),
            ],
        ),
    ]
